package com.resq.ResQ_Plate.service;

import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.io.File;
import java.time.YearMonth;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${spring.mail.username}")
    private String fromEmail;

    /**
     * Sends the monthly tax deduction Excel report to the donor's email.
     *
     * @param toEmail   Donor's email address
     * @param donorName Donor's display name
     * @param yearMonth The report period (e.g. 2026-03)
     * @param filePath  Absolute path to the generated .xlsx file
     */
    public void sendTaxReport(String toEmail, String donorName, YearMonth yearMonth, String filePath) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject("ResQ Plate — Tax Deduction Report for " + yearMonth);

            String htmlBody = String.format("""
                    <html>
                    <body style="font-family: Arial, sans-serif; color: #1f2937; background: #f9fafb; padding: 20px;">
                      <div style="max-width: 600px; margin: auto; background: white; border-radius: 12px;
                                  padding: 32px; box-shadow: 0 4px 20px rgba(0,0,0,0.08);">
                        <div style="text-align:center; margin-bottom: 24px;">
                          <h1 style="color: #16a34a; margin: 0;">🌿 ResQ Plate</h1>
                          <p style="color: #6b7280; margin: 4px 0;">Zero-Waste Food Rescue Network</p>
                        </div>
                        <h2 style="color: #111827;">Hello %s,</h2>
                        <p>Thank you for your generous food donations through <strong>ResQ Plate</strong>.
                           Your contributions are making a real difference in your community!</p>
                        <div style="background: #f0fdf4; border-left: 4px solid #16a34a;
                                    padding: 16px; border-radius: 4px; margin: 20px 0;">
                          <p style="margin: 0; font-weight: bold;">📋 Tax Deduction Report: %s</p>
                          <p style="margin: 4px 0 0; color: #374151;">
                            Please find your monthly donation summary attached. This document may be
                            used for tax deduction purposes as per your local regulations.
                          </p>
                        </div>
                        <p>Present this report to your accounting team along with any applicable
                           local food donation guidelines.</p>
                        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;">
                        <p style="color: #9ca3af; font-size: 12px;">
                          This is an automated report generated by ResQ Plate.
                          If you have any questions, please contact your ResQ Plate administrator.
                        </p>
                      </div>
                    </body>
                    </html>
                    """, donorName, yearMonth);

            helper.setText(htmlBody, true);

            // Attach the Excel report
            FileSystemResource file = new FileSystemResource(new File(filePath));
            helper.addAttachment("ResQPlate_TaxReport_" + yearMonth + ".xlsx", file);

            mailSender.send(message);
            log.info("Tax report emailed to {} for period {}", toEmail, yearMonth);

        } catch (Exception e) {
            log.error("Failed to send tax report email to {}: {}", toEmail, e.getMessage(), e);
            throw new RuntimeException("Email delivery failed: " + e.getMessage(), e);
        }
    }
}
